import "./globals.css";
import Navbar from "@/Components/navbar/Navbar";
import Footer from "@/Components/footer/Footer";

import {Montserrat } from "next/font/google";
const bodyFont = Montserrat({ subsets: ["latin"],
weight:["400","900"] });


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={bodyFont.className}>
       <div className="container">
        <Navbar />
        {children}
        <Footer />
       </div>

      </body>
    </html>
  );
}
